src/Web/Controllers/ApplicationsController.cs
using System;
using System.Threading.Tasks;
using Hayate.Core.Applications;
using Hayate.Core.Instances;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ApplicationId = Hayate.Core.Applications.ApplicationId;
using Environment = Hayate.Core.Applications.Environment;

namespace Hayate.Web.Controllers
{
    [Authorize]
    public sealed class ApplicationsController : Controller
    {
        private readonly IApplicationRegistry _applications;

        public ApplicationsController(IApplicationRegistry applications)
        {
            _applications = applications;
        }

        [HttpGet]
        public async Task<IActionResult> Index(Guid? id)
        {
            if (id == null)
            {
                var applications = await _applications.ListAsync();
                return View(applications);
            }

            return await ApplicationAsync(id.Value);
        }

        private async Task<IActionResult> ApplicationAsync(Guid id)
        {
            var application = await _applications.FindAsync(new ApplicationId(id));

            return this.ViewOrNotFound("Item", application);
        }

        [HttpGet]
        public async Task<IActionResult> Preview(Guid id, string environmentName)
        {
            var environment = await FindEnvironmentAsync(id, environmentName);

            return this.ViewOrNotFound(environment);
        }

        [HttpPost]
        [ActionName("Preview")]
        public async Task<IActionResult> PostPreview(Guid id, string environmentName, InstanceTransition transition)
        {
            var environment = await FindEnvironmentAsync(id, environmentName);
            environment.Transit(transition);

            if (environment.IsNotFound) return NotFound();

            return RedirectToProxy(environment);
        }

        private IActionResult RedirectToProxy(Environment environment)
        {
            // ToDo EnvironmentId と InstanceId をごっちゃにするのは良くないかも...
            return this.RedirectToLocal($"/_/proxy/{environment.Id.ToString()}");
        }

        private Task<Environment> FindEnvironmentAsync(Guid id, string environmentName)
        {
            return _applications.FindEnvironmentAsync(new ApplicationId(id),
                new EnvironmentName(environmentName));
        }
    }
}

src/Web/Controllers/RegistrationsController.cs
using System.Threading.Tasks;
using Hayate.Core.Projects;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Hayate.Web.Controllers
{
    [Authorize]
    public sealed class RegistrationsController : Controller
    {
        private readonly IProjectRegistry _projects;

        public RegistrationsController(IProjectRegistry projects)
        {
            _projects = projects;
        }

        public async Task<IActionResult> Index()
        {
            var projects = await _projects.ListAsync();
            return View(projects);
        }

        [HttpPost]
        public async Task<IActionResult> Project(string id)
        {
            var project = await FindOrCreateAsync(id);
            return RedirectToAction("Index", "Applications", new {project.Id});
        }

        private async Task<Project> FindOrCreateAsync(string targetId)
        {
            return await _projects.FindOrRegisterAsync(new TargetProjectId(targetId));
        }
    }
}

src/Web/Views/Applications/Index.cshtml
@model Hayate.Core.Applications.ApplicationCollection

@{
    ViewBag.Title = "title";
}

<div class="row">
    <h2 class="col-sm-8">Applications</h2>
    <div class="col-sm-4 text-right">
        <a asp-controller="Registrations" asp-action="Index" class="btn btn-success">New Application</a>
    </div>
</div>

@if (!Model.IsEmpty)
{
    <table class="table">
        <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                ID
            </th>
        </tr>
        </thead>
        <tbody>
        @foreach (var application in Model)
        {
            <tr>
                <td>
                    <a asp-action="Index" asp-route-id="@application.Id">@application.Name</a>
                </td>
                <td>
                    @application.Id
                </td>
            </tr>
        }
        </tbody>
    </table>
}

src/Web/Views/Applications/Item.cshtml
@model Hayate.Core.Applications.Application

@{
    ViewBag.Title = @Model.Name;
}

<section class="container">
    <div class="row">
        <div class="col-sm-8">
            <h3>@Model.Name</h3>
        </div>
        <div class="col-sm-4">
            <a href="@Model.SiteUrl" target="gitlab">
                <i class="fa fa-external-link-alt"></i>
                Project Site
            </a>
        </div>
    </div>

    <table class="table">
        <thead>
        <tr>
            <th>Environment</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var instance in Model.Environments)
        {
            <tr>
                <td>
                    <a asp-action="Preview" asp-route-id="@Model.Id" asp-route-environmentName="@instance.Name">
                        <span class="font-weight-bold">@instance.Name</span>
                        <i class="fa fa-external-link-alt"></i>
                    </a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</section>

src/Web/Views/Applications/Preview.cshtml
@using Hayate.Core.Instances
@model Hayate.Core.Applications.Environment

@{
    ViewBag.Title = Model.Name;
}

<h2>
    <a asp-action="Index" asp-route-id="@Model.Application.Id">
        @Model.Application.Name
    </a>
    /
    @Model.Name
</h2>

<section class="text-center" style="margin-bottom: 2rem; margin-top: 2rem;">
    <form method="post" asp-route-id="@Model.Application.Id" target="_blank">
        <div class="btn-group">
            <button type="submit" class="btn btn-success btn-lg" asp-route-environmentName="@Model.Name" asp-route-transition="@InstanceTransition.Running.ToString()">
                <i class="fas fa-eye"></i>
                Preview
            </button>
            <button type="button" class="btn btn-success btn-lg dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <div class="dropdown-menu">
                <button type="submit" class="dropdown-item" asp-route-environmentName="@Model.Name" asp-route-transition="@InstanceTransition.Restarted.ToString()" disabled="@(!Model.CanTransit(InstanceTransition.Restarted))">
                    <i class="fas fa-sync"></i>
                    Restart
                </button>
                <button type="submit" class="dropdown-item" asp-route-environmentName="@Model.Name" asp-route-transition="@InstanceTransition.TryUpgrade.ToString()" disabled="@(!Model.CanTransit(InstanceTransition.TryUpgrade))">
                    <i class="fas fa-arrow-alt-circle-up"></i>
                    Upgrade
                </button>
            </div>
        </div>
    </form>
</section>

<section id="terminal-list">
    <environment include="Development">
        <script src="~/lib/xtermjs/xterm.js"></script>
        <script src="~/lib/xtermjs/attach.js"></script>
        <script src="~/lib/xtermjs/fit.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/xtermjs/xterm.min.js"></script>
        <script src="~/lib/xtermjs/attach.min.js"></script>
        <script src="~/lib/xtermjs/fit.min.js"></script>
    </environment>

    <input type="hidden" id="instance-id" value="@Model.Id.ToString()">

    <ul id="terminal-tab-items" class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#logs" role="tab">Logs</a>
        </li>
        <li class="nav-item plus">
            <a id="new-tty" class="nav-link">
                <i class="fas fa-plus"></i>
            </a>
        </li>
    </ul>

    <div id="terminal-tab-pages" class="tab-content" style="width: 100%;">
        <div id="logs" role="tabpanel" class="tab-pane show active" style="position: relative;">
            <div style="padding-right: 2rem; position: absolute; width: 100%; z-index: 10;" class="text-right">
                <a id="start-instance-logs" style="color: white;" href="#">
                    <i class="fas fa-play"></i>
                    Show logs
                </a>
            </div>
            <div class="terminal" data-type="logs" style="width: 100%; position: absolute; z-index: 5;"></div>
        </div>
    </div>

    <template id="tab-item-template">
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#tty0" role="tab">
                Terminal#0
            </a>
        </li>
    </template>

    <template id="tab-page-template">
        <div id="tty0" role="tabpanel" class="tab-pane">
            <div class="terminal" data-type="shell"></div>
        </div>
    </template>
    <script src="~/scripts/terminal-window.js" type="module"></script>
</section>