src/Web/Controllers/ApplicationsController.cs
using System;
using System.Threading.Tasks;
using Hayate.Core.Applications;
using Hayate.Core.Instances;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ApplicationId = Hayate.Core.Applications.ApplicationId;
using Environment = Hayate.Core.Applications.Environment;

namespace Hayate.Web.Controllers
{
    [Authorize]
    public sealed class ApplicationsController : Controller
    {
        private readonly IApplicationRegistry _applications;

        public ApplicationsController(IApplicationRegistry applications)
        {
            _applications = applications;
        }

        [HttpGet]
        public async Task<IActionResult> Index(Guid? id)
        {
            if (id == null)
            {
                var applications = await _applications.ListAsync();
                return View(applications);
            }

            return await ApplicationAsync(id.Value);
        }

        private async Task<IActionResult> ApplicationAsync(Guid id)
        {
            var application = await _applications.FindAsync(new ApplicationId(id));

            return this.ViewOrNotFound("Item", application);
        }

        [HttpGet]
        public async Task<IActionResult> Preview(Guid id, string environmentName)
        {
            var environment = await FindEnvironmentAsync(id, environmentName);

            return this.ViewOrNotFound(environment);
        }

        [HttpPost]
        [ActionName("Preview")]
        public async Task<IActionResult> PostPreview(Guid id, string environmentName, InstanceTransition transition)
        {
            var environment = await FindEnvironmentAsync(id, environmentName);
            environment.Transit(transition);

            if (environment.IsNotFound) return NotFound();

            return RedirectToProxy(environment);
        }

        private IActionResult RedirectToProxy(Environment environment)
        {
            // ToDo EnvironmentId と InstanceId をごっちゃにするのは良くないかも...
            return this.RedirectToLocal($"/_/proxy/{environment.Id.ToString()}");
        }

        private Task<Environment> FindEnvironmentAsync(Guid id, string environmentName)
        {
            return _applications.FindEnvironmentAsync(new ApplicationId(id),
                new EnvironmentName(environmentName));
        }
    }
}

src/Web/Controllers/SettingsController.cs
using System.Threading.Tasks;
using Hayate.Core.Tokens;
using Hayate.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Hayate.Web.Controllers
{
    [Authorize]
    public sealed class SettingsController : Controller
    {
        private readonly IVerifiedGitLabPatRegistrationService _pats;

        public SettingsController(IVerifiedGitLabPatRegistrationService pats)
        {
            _pats = pats;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> PersonalAccessToken()
        {
            var token = await _pats.LoadVerifiedPatAsync();

            return View(new PersonalAccessTokenSettings
            {
                PersonalAccessToken = token.Token.ToString(),
                Verified = token.Verified,
                GitLabSettingsUri = "http://gitlab.hayate.example.jp/profile/personal_access_tokens"
            });
        }

        [HttpPost]
        public async Task<IActionResult> PersonalAccessToken(PersonalAccessTokenSettings settings)
        {
            await _pats.SavePatAsync(new PersonalAccessToken(settings.PersonalAccessToken));
            return RedirectToAction("PersonalAccessToken");
        }
    }
}

src/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - はやて</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap.css">
        <link rel="stylesheet" href="~/lib/xtermjs/xterm.css">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap.min.css">
        <link rel="stylesheet" href="~/lib/xtermjs/xterm.min.css">
    </environment>

    <link rel="stylesheet" href="~/css/layout.css">
    <link rel="stylesheet" href="~/lib/fontawesome/css/fontawesome-all.css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" asp-controller="Home" asp-action="Index">はやて</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" asp-controller="Applications" asp-action="Index" asp-route-id="@null">Applications</a>
            </li>
        </ul>
    </div>

    <ul class="nav">
        @{
            if (User.Identity.IsAuthenticated)
            {
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbar-user-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="@User.FindFirst("urn:hayate:avatar")?.Value" class="rounded-circle" style="height: 1.5rem; width: 1.5rem;">
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-user-dropdown" style="position: absolute; right: 0; top: 0; transform: translate3d(-5rem, 38px, 0);">
                        <span class="dropdown-header">@User.Identity.Name</span>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-controller="Settings" asp-action="Index">Settings</a>
                        <div class="dropdown-divider"></div>
                        <form asp-controller="Account" asp-action="Logout">
                            <button class="dropdown-item">Sign Out</button>
                        </form>
                    </div>
                </li>
            }
            else
            {
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Account" asp-action="Login">Sign In</a>
                </li>
            }
        }
    </ul>
</nav>

<section class="container">
    @RenderBody()
</section>

<footer class="navbar navbar-dark bg-dark fixed-bottom">
    <section class="container">
        <span class="text-muted">Copyright &copy; 2018 Hayate Team. All Rights Reserved.</span>
    </section>
</footer>

<environment include="Development">
    <script src="~/lib/jquery-3.2.1.slim.js"></script>
    <script src="~/lib/popper.js"></script>
    <script src="~/lib/bootstrap.js"></script>
</environment>
<environment exclude="Development">
    <script src="~/lib/jquery-3.2.1.slim.min.js"></script>
    <script src="~/lib/popper.min.js"></script>
    <script src="~/lib/bootstrap.min.js"></script>
</environment>
</body>
</html>

src/Web/Views/Shared/_PersonalSettingsNav.cshtml
@using Hayate.Web.Controllers
<nav>
    <div class="nav nav-tabs" role="tablist">
        <a class="nav-item nav-link@(Model == nameof(SettingsController.Index) ? " active" : "")" asp-action="Index" asp-controller="Settings">Global</a>
        <a class="nav-item nav-link@(Model == nameof(SettingsController.PersonalAccessToken) ? " active" : "")" asp-action="PersonalAccessToken" asp-controller="Settings">Personal Access Token</a>
    </div>
</nav>